### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it.

### ISSUE THREAD

**Issue by fqz100** [Vaibhav2002/Healthify#1]

**Comment by Vaibhav2002** [comment]
> 

We should not make our google-services.json public as it has vital data.

Making it public is a security flaw. Anyone can make a wrong use of it.

So it is best to keep it private.

To make the project work, just create your own project in firebase, enable firestore and download the Google-services.json and paste in the app directory.

**Comment by fqz100** [comment]
> > 
> 
> We should not make our google-services.json public as it has vital data.
> 
> Making it public is a security flaw. Anyone can make a wrong use of it.
> 
> So it is best to keep it private.
> 
> To make the project work, just create your own project in firebase, enable firestore and download the Google-services.json and paste in the app directory.

OK, I got it, thanks!
